// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DrawRedRect$Sparrow from "./DrawRedRect.bs.js";

var drawRedRect = DrawRedRect$Sparrow.drawRedRect;

export {
  drawRedRect ,
}
/* No side effect */
